export const test0 = [
  {
    name: "Braids, Arisen Nightmare",
    type: "Legendary Creature — Nightmare",
    text: "At the beginning of your end step, you may sacrifice an artifact, creature, enchantment, land, or planeswalker. If you do, each opponent may sacrifice a permanent of their choice that shares a card type with it. For each opponent who doesn't, that player loses 2 life and you draw a card.",
    manaCost: "{1}{B}{B}",
    power: "3",
    toughness: "3",
    rarity: "rare",
    setCode: "DMU",
    manaValue: 3,
    edhrecRank: 317,
    edhrecSaltiness: 1,
  },
  {
    name: "Braids, Arisen Nightmare",
    type: "Legendary Creature — Nightmare",
    text: "At the beginning of your end step, you may sacrifice an artifact, creature, enchantment, land, or planeswalker. If you do, each opponent may sacrifice a permanent of their choice that shares a card type with it. For each opponent who doesn't, that player loses 2 life and you draw a card.",
    manaCost: "{1}{B}{B}",
    power: "3",
    toughness: "3",
    rarity: "rare",
    setCode: "GDY",
    manaValue: 3,
    edhrecRank: 317,
    edhrecSaltiness: 1,
  },
  {
    name: "Braids, Cabal Minion",
    type: "Legendary Creature — Human Minion",
    text: "At the beginning of each player's upkeep, that player sacrifices an artifact, creature, or land of their choice.",
    manaCost: "{2}{B}{B}",
    power: "2",
    toughness: "2",
    rarity: "rare",
    setCode: "EMA",
    manaValue: 4,
    edhrecRank: null,
    edhrecSaltiness: null,
  },
  {
    name: "Braids, Arisen Nightmare",
    type: "Legendary Creature — Nightmare",
    text: "At the beginning of your end step, you may sacrifice an artifact, creature, enchantment, land, or planeswalker. If you do, each opponent may sacrifice a permanent of their choice that shares a card type with it. For each opponent who doesn't, that player loses 2 life and you draw a card.",
    manaCost: "{1}{B}{B}",
    power: "3",
    toughness: "3",
    rarity: "rare",
    setCode: "PWCS",
    manaValue: 3,
    edhrecRank: 318,
    edhrecSaltiness: 1,
  },
  {
    name: "Braids, Arisen Nightmare",
    type: "Legendary Creature — Nightmare",
    text: "At the beginning of your end step, you may sacrifice an artifact, creature, enchantment, land, or planeswalker. If you do, each opponent may sacrifice a permanent of their choice that shares a card type with it. For each opponent who doesn't, that player loses 2 life and you draw a card.",
    manaCost: "{1}{B}{B}",
    power: "3",
    toughness: "3",
    rarity: "rare",
    setCode: "DMU",
    manaValue: 3,
    edhrecRank: 317,
    edhrecSaltiness: 1,
  },
  {
    name: "Braids, Arisen Nightmare",
    type: "Legendary Creature — Nightmare",
    text: "At the beginning of your end step, you may sacrifice an artifact, creature, enchantment, land, or planeswalker. If you do, each opponent may sacrifice a permanent of their choice that shares a card type with it. For each opponent who doesn't, that player loses 2 life and you draw a card.",
    manaCost: "{1}{B}{B}",
    power: "3",
    toughness: "3",
    rarity: "rare",
    setCode: "PRM",
    manaValue: 3,
    edhrecRank: 318,
    edhrecSaltiness: 1,
  },
  {
    name: "Braids, Arisen Nightmare",
    type: "Legendary Creature — Nightmare",
    text: "At the beginning of your end step, you may sacrifice an artifact, creature, enchantment, land, or planeswalker. If you do, each opponent may sacrifice a permanent of their choice that shares a card type with it. For each opponent who doesn't, that player loses 2 life and you draw a card.",
    manaCost: "{1}{B}{B}",
    power: "3",
    toughness: "3",
    rarity: "rare",
    setCode: "PDMU",
    manaValue: 3,
    edhrecRank: 318,
    edhrecSaltiness: 1,
  },
  {
    name: "Braids, Conjurer Adept",
    type: "Legendary Creature — Human Wizard",
    text: "At the beginning of each player's upkeep, that player may put an artifact, creature, or land card from their hand onto the battlefield.",
    manaCost: "{2}{U}{U}",
    power: "2",
    toughness: "2",
    rarity: "rare",
    setCode: "CMM",
    manaValue: 4,
    edhrecRank: 4720,
    edhrecSaltiness: 0,
  },
  {
    name: "Braids's Frightful Return",
    type: "Enchantment — Saga",
    text: "Read ahead (Choose a chapter and start with that many lore counters. Add one after your draw step. Skipped chapters don't trigger. Sacrifice after III.)\\\\nI — You may sacrifice a creature. If you do, each opponent discards a card.\\\\nII — Return target creature card from your graveyard to your hand.\\\\nIII — Target opponent may sacrifice a nonland, nontoken permanent of their choice. If they don't, they lose 2 life and you draw a card.",
    manaCost: "{2}{B}",
    power: null,
    toughness: null,
    rarity: "uncommon",
    setCode: "DMU",
    manaValue: 3,
    edhrecRank: 9330,
    edhrecSaltiness: 0,
  },
  {
    name: "Braids, Conjurer Adept",
    type: "Legendary Creature — Human Wizard",
    text: "At the beginning of each player's upkeep, that player may put an artifact, creature, or land card from their hand onto the battlefield.",
    manaCost: "{2}{U}{U}",
    power: "2",
    toughness: "2",
    rarity: "rare",
    setCode: "PLC",
    manaValue: 4,
    edhrecRank: 4720,
    edhrecSaltiness: 0,
  },
];

export const test = [
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "common",
    setCode: "TMP",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "uncommon",
    setCode: "30A",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "common",
    setCode: "SCD",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "uncommon",
    setCode: "FBB",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "common",
    setCode: "BRB",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "common",
    setCode: "PLST",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "common",
    setCode: "ME4",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "uncommon",
    setCode: "S99",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "uncommon",
    setCode: "4ED",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
  {
    name: "Counterspell",
    type: "Instant",
    text: "Counter target spell.",
    manaCost: "{U}{U}",
    power: null,
    toughness: null,
    rarity: "common",
    setCode: "CMM",
    manaValue: 2,
    edhrecRank: 19,
    edhrecSaltiness: 0,
  },
];
